const CONSTANTS = {
  OFFICE_API_URL: process.env.REACT_APP_OFFICE_API_URL,
  NOTIFIER_API_URL: process.env.REACT_APP_NOTIFIER_API_URL,
  VOIP_API_URL: process.env.REACT_APP_VOIP_API_URL,
  MEDIA_API_URL: process.env.REACT_APP_MEDIA_API_URL,
  ADMIN_API_URL: process.env.REACT_APP_ADMIN_API_URL,
  PBX_API_URL: process.env.REACT_APP_PBX_API_URL,
  TEST_TENANT_ID: 'alex1',
  ENV: process.env.REACT_APP_ENV,
  GOOGLE_ANALYTICS_MEASURMENT_ID: process.env.REACT_APP_GA_MEASURMENT_ID,
  LOGROCKET_APP_ID: process.env.REACT_APP_LOGROCKET_APP_ID,
};

const AUTHORIZATION_TYPE = Object.freeze({
  USER: 'user',
  PATIENT: 'patient',
  TENANT: 'tenant',
});

export default CONSTANTS;
export {
  AUTHORIZATION_TYPE,
};
