const SET_UNREAD_COUNT_MESSAGE = 'SET_UNREAD_COUNT_MESSAGE';
const INCREASE_UNREAD_COUNT_MESSAGE = 'INCREASE_UNREAD_COUNT_MESSAGE';
const RESET_UNREAD_COUNT_MESSAGE = 'RESET_UNREAD_COUNT_MESSAGE';
const TOGGLE_BUBBLE_CHAT = 'TOGGLE_BUBBLE_CHAT';
const SET_CHANNELS = 'SET_CHANNELS';

export {
  SET_UNREAD_COUNT_MESSAGE,
  INCREASE_UNREAD_COUNT_MESSAGE,
  RESET_UNREAD_COUNT_MESSAGE,
  TOGGLE_BUBBLE_CHAT,
  SET_CHANNELS,
};
