image: node:16

options:
  size: 2x # All steps in this repo get 8GB memory

pipelines:
  branches:
    dev:
      - step:
          caches:
            - node
          script:
            - yarn install
            - export CI=false
            - yarn run build:dev
            - apt-get update && apt-get install -y awscli
            - aws s3 sync build/ s3://kasper-dev-office-ui --acl public-read
            - aws cloudfront create-invalidation --distribution-id E2UO96OBWQ4WSU --paths "/*"
    stage:
      - step:
          script:
            - yarn install
            - export CI=false
            - yarn run build:stage
            - apt-get update && apt-get install -y awscli
            - aws s3 sync build/ s3://kasper-stage-office-ui --acl public-read
            - aws cloudfront create-invalidation --distribution-id E35KHBEHTWI2K1 --paths "/*"
    master:
      - step:
          script:
            - yarn install
            - export CI=false
            - yarn run build:prod
            - apt-get update && apt-get install -y awscli
            - aws s3 sync build/ s3://kasper-prod-office-ui --acl public-read
            - aws cloudfront create-invalidation --distribution-id ENVAHDQTLCAKE --paths "/*"
