const SET_STORE = "SET_STORE";
const INIT = "INIT";
const SET_INVALID_TENANT = "SET_INVALID_TENANT";
const SET_AUTH_DATA = "SET_AUTH_DATA";
const LOGIN = "LOGIN";
const REFRESH_USER = "REFRESH_USER";
const LOG_OUT = "LOG_OUT";
const FORCE_PASSWORD_CHANGE = "FORCE_PASSWORD_CHANGE";
const SET_LOADED_AUTH = "SET_LOADED_AUTH";
export {
  SET_STORE,
  INIT,
  SET_INVALID_TENANT,
  SET_AUTH_DATA,
  LOGIN,
  REFRESH_USER,
  LOG_OUT,
  FORCE_PASSWORD_CHANGE,
  SET_LOADED_AUTH,
};
